### ISSUE TITLE
Why we list inaccessible benchmark?

### ISSUE THREAD

**Issue by zhimin-z** [tjunlp-lab/Awesome-LLMs-Evaluation-Papers#14]
Where are the results of these two benchmarks for domain evaluation in the [OpenEval](http://openeval.org.cn/rank) leaderboard?
![image](https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/assets/8592144/ee47522d-83c5-4f90-9626-535300e91adc)

**Comment by allen3ai** [comment]
Thanks for the attention, it was previously because the domain was being filed and is now accessible.

**Comment by allen3ai** [comment]
In addition, OpenEval is not a benchmark, but a evaluation platform for large Chinese models, including several Chinese benchmarks.

**Comment by zhimin-z** [comment]
> In addition, OpenEval is not a benchmark, but a evaluation platform for large Chinese models, including several Chinese benchmarks.

Thanks, @allen3ai It seems this could not click...
![image](https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/assets/8592144/f8a12164-23f3-4245-b737-fa01ed965b9f)

**Comment by zhimin-z** [comment]
> Thanks for the attention, it was previously because the domain was being filed and is now accessible.

BTW, where are the results of these two benchmarks for domain evaluation?
![image](https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/assets/8592144/ee47522d-83c5-4f90-9626-535300e91adc)

**Comment by allen3ai** [comment]
Hi, thanks for your questions.
For Github's issue, it has not built, because OpenEval still are fixing, and we are discussing about this. Please waiting for this.
For two domain benchmarks, "罪名法务智能数据集" is testing now， but we find a better law benchmark for LLMs, so we may take place of  this benchmark. And  "WGLaw" is tested now, we will release results for a moment. This benchmark is collected from Yellow River Conservancy Commission of the Ministry of Water Resources. But we find general results are still worse, and we will add these new results  of domain benchmarks soon.

**Comment by zhimin-z** [comment]
![image](https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/assets/8592144/e6309637-7fd7-4b5f-a706-887553be6492)
Does it work?
